/*
* File: PopulationCensus.sql
* Challenge: Basic Join
* Author: Riley Jordan
* Date: February 15, 2025
* Database: Oracle
*/

-- Table Definitions
CREATE TABLE CITY (
    ID NUMBER CONSTRAINT city_pk PRIMARY KEY,
    NAME VARCHAR2(17) NOT NULL,
    COUNTRYCODE VARCHAR2(3) NOT NULL,
    DISTRICT VARCHAR2(20) NOT NULL,
    POPULATION NUMBER NOT NULL
);

CREATE TABLE COUNTRY (
    CODE VARCHAR2(3) CONSTRAINT country_pk PRIMARY KEY,
    NAME VARCHAR2(52) NOT NULL,
    CONTINENT VARCHAR2(13) NOT NULL,
    REGION VARCHAR2(26) NOT NULL,
    SURFACEAREA NUMBER NOT NULL,
    INDEPYEAR NUMBER,
    POPULATION NUMBER NOT NULL,
    LIFEEXPECTANCY NUMBER,
    GNP NUMBER,
    GNPOID NUMBER,
    LOCALNAME VARCHAR2(45) NOT NULL,
    GOVERNMENTFORM VARCHAR2(45) NOT NULL,
    HEADOFSTATE VARCHAR2(60),
    CAPITAL NUMBER,
    CODE2 VARCHAR2(2) NOT NULL
);

-- Data Insertion
INSERT ALL 
    INTO CITY(ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) VALUES (1, 'Kabul', 'AFG', 'Kabol', 1780000)
    INTO CITY(ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) VALUES (2, 'Qandahar', 'AFG', 'Qandahar', 237500)
    INTO CITY(ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) VALUES (3, 'Herat', 'AFG', 'Herat', 186800)
    INTO CITY(ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) VALUES (4, 'Mazar-e-Sharif', 'AFG', 'Balkh', 127800)
    INTO CITY(ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) VALUES (5, 'Amsterdam', 'NLD', 'Noord-Holland', 731200)
    INTO CITY(ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) VALUES (6, 'Rotterdam', 'NLD', 'Zuid-Holland', 593321)
SELECT * FROM dual;

INSERT ALL
    INTO COUNTRY(CODE, NAME, CONTINENT, REGION, SURFACEAREA, INDEPYEAR, POPULATION, LIFEEXPECTANCY, GNP, GNPOID, LOCALNAME, GOVERNMENTFORM, HEADOFSTATE, CAPITAL, CODE2) VALUES ('AFG', 'Afghanistan', 'Asia', 'Southern and Central Asia', 652090, 1919, 22720000, 45.9, 5976, 5998, 'Afganistan/Afqanestan', 'Islamic Emirate', 'Mohammad Omar', 1, 'AF')
    INTO COUNTRY(CODE, NAME, CONTINENT, REGION, SURFACEAREA, INDEPYEAR, POPULATION, LIFEEXPECTANCY, GNP, GNPOID, LOCALNAME, GOVERNMENTFORM, HEADOFSTATE, CAPITAL, CODE2) VALUES ('NLD', 'Netherlands', 'Europe', 'Western Europe', 41526, 1581, 15864000, 78.3, 371362, 2801, 'Nederland', 'Constitutional Monarchy', 'Beatrix', 5, 'NL')
SELECT * FROM dual;

-- Query Section 1: Sum of population where contintent is asia
/* Sum of population where continent is Asia */
SELECT SUM(C.POPULATION) AS TotalPopulation
FROM CITY C
JOIN COUNTRY CO ON C.COUNTRYCODE = CO.CODE
WHERE CO.CONTINENT = 'Asia';

/* all names of cities where continent is africa */
SELECT C.NAME AS CITYNAMES 
FROM CITY C
JOIN COUNTRY CO ON C0.CODE = C.COUNTRYCODE
WHERE CO.CONTINENT = 'Africa';

/* names of all contintents (country,continent) and population rounded down of the city. */
SELECT CO.CONTINENT, FLOOR(AVG(C.POPULATION)) AS AVG_CITY_POPULATION
FROM COUNTRY CO
JOIN CITY C ON CO.CODE = C.COUNTRYCODE
GROUP BY CO.CONTINENT;

-- Cleanup Section
Commit;
DROP TABLE CITY;